In [1]:
# 1. Saving array
import numpy as np
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [2]:
np.save('saved_array',arr)

In [6]:
# 2. Retrive it
buffer=np.load('saved_array.npy')
print(buffer)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [8]:
# 3. Save as zip
brr=np.arange(20,0,-1)
print(brr)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [22]:
np.savez('zipped_file',arr=arr,brr=brr)

In [23]:
# 4. Load zip file
loaded=np.load('zipped_file.npz')
print(loaded)

In [26]:
# 5. Extracting it
loaded_file_one=loaded['arr']
print(loaded_file_one)
print("")
loaded_file_two=loaded['brr']
print(loaded_file_two)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [27]:
# 6. Save as text
np.savetxt('text_file.txt',arr,delimiter=',')
arr_txt_file = np.loadtxt('text_file.txt',delimiter=',')
print(arr)
print('')
print(arr_txt_file)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
