In [1]:
# 1. Importing package
import numpy as np

In [2]:
# 2. Builtin math functions
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# 3. generating array with interval samples
vec = np.linspace(1,6,10)
print(vec)

[1.         1.55555556 2.11111111 2.66666667 3.22222222 3.77777778
 4.33333333 4.88888889 5.44444444 6.        ]


In [11]:
# 4. default arrays
arr_1 = np.zeros([5,3])
print(arr_1)
print("")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [12]:
arr_2 = np.ones((3,5))
print(arr_2)
print("")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



In [13]:
arr_3 = np.eye(5)
print(arr_3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
# 5. Operations in arraya
arr_1 = np.arange(1,6)
arr_2 = np.arange(4,9)
print(arr_1)
print(arr_2)
print(arr_1+arr_2)
print(arr_1*arr_2)
print(1/arr_1)


[1 2 3 4 5]
[4 5 6 7 8]
[ 5  7  9 11 13]
[ 4 10 18 28 40]
[1.         0.5        0.33333333 0.25       0.2       ]


In [31]:
# 6. Matrix multiply
arr = np.arange(4,9).reshape(5,1)
print(arr,"Shape: "+str(arr.shape),sep="\t")
print("")
vec=np.arange(1,6).reshape(1,5)
print(vec,"Shape: "+str(vec.shape),sep="\t")

[[4]
 [5]
 [6]
 [7]
 [8]]	Shape: (5, 1)

[[1 2 3 4 5]]	Shape: (1, 5)


In [34]:
product = np.matmul(arr,vec)
print("Product Matrix: \n",product)

Product Matrix: 
 [[ 4  8 12 16 20]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]
 [ 7 14 21 28 35]
 [ 8 16 24 32 40]]
