In [3]:
# 1. Slicing
import numpy as np
arr=np.array([['a','b','c'],['x','y','z']])
print(arr[1,0:])

['x' 'y' 'z']


In [5]:
print(arr[1,::-1])

['z' 'y' 'x']


In [8]:
# 2. Datatypes 
character=np.array([1,2,3,4,5],dtype='i')
string=np.array(['koel','siyan','jazz'],dtype='S')

In [9]:
print(character)
print(character.dtype)

[1 2 3 4 5]
int32


In [10]:
print(string)
print(string.dtype)

[b'koel' b'siyan' b'jazz']
|S5


In [15]:
# 3. Datatype casting
alpha=np.array([9,0,3,0,6,4])
value=alpha.astype(bool)
print(value)

[ True False  True False  True  True]


In [17]:
# 4. Copying array
tmp=alpha.copy()
tmp[0]=10
print(tmp)

[10  0  3  0  6  4]


In [18]:
# 5. View affects array
disp=character.view()
disp[0]=0
print(disp)

[0 2 3 4 5]


In [19]:
# 6. changing original_array affects 
character[2]=11
print(character)

[ 0  2 11  4  5]


In [23]:
# 7. base differs
print("Copied :",tmp.base,"Original :",disp.base,sep="\n")

Copied :
None
Original :
[ 0  2 11  4  5]
