In [9]:
# 1. Concatenate arrays
import numpy as np
first=np.array([[1,2,3],[4,5,6]])
second=np.array([['a','b','c'],['e','f','g']])

In [12]:
print ("First Array:" )
print(first)
print("Second Array:")
print(second)

First Array:
[[1 2 3]
 [4 5 6]]
Second Array:
[['a' 'b' 'c']
 ['e' 'f' 'g']]


In [13]:
# 2. joining arrays in same axis
print(np.concatenate((first,second),axis=0))

[['1' '2' '3']
 ['4' '5' '6']
 ['a' 'b' 'c']
 ['e' 'f' 'g']]


In [17]:
# 3. joining arrays in new axis
print(np.stack((first,second),axis=1))

[[['1' '2' '3']
  ['a' 'b' 'c']]

 [['4' '5' '6']
  ['e' 'f' 'g']]]


In [19]:
# 4. joining along x-axis
arr_1 = np.array([[1, 2],[4, 3]])
arr_2 = np.array([[4, 5],[7, 6]])
print(np.hstack((arr_1, arr_2)))

[[1 2 4 5]
 [4 3 7 6]]


In [20]:
# 5. joining along y-axis
print(np.vstack((arr_1, arr_2)))

[[1 2]
 [4 3]
 [4 5]
 [7 6]]


In [30]:
# 6. Transposing an array
arr_3=np.transpose(np.hstack((arr_1,arr_2)))
print(arr_3)

[[1 4]
 [2 3]
 [4 7]
 [5 6]]


In [32]:
# 7.  change to 1D
print (arr_3.flatten() )
print("Flattening across column wise: ")
print (arr_3.flatten(order = 'F'))
print("Flattening across row wise: ")
print (arr_3.flatten(order = 'C'))

[1 4 2 3 4 7 5 6]
Flattening across column wise: 
[1 2 4 5 4 3 7 6]
Flattening across row wise: 
[1 4 2 3 4 7 5 6]


In [41]:
# 8. resizing the array
arr=np.array([1,2,3,4,5,6])
print("Original Array Shape: ")
print(arr.shape)
print("Resized array Shape: ")
print(np.resize(arr,(3,2)).shape)
print("Resized array: ")
arr=np.resize(arr,(3,2))
print(arr)

Original Array Shape: 
(6,)
Resized array Shape: 
(3, 2)
Resized array: 
[[1 2]
 [3 4]
 [5 6]]


In [44]:
# 9. appending array elements across x-axis
print(np.append(arr,arr_3,axis=0))

[[1 2]
 [3 4]
 [5 6]
 [1 4]
 [2 3]
 [4 7]
 [5 6]]


In [47]:
# 10.appending across y axis
print(np.append(arr,[[7],[8],[9]],axis=1))

[[1 2 7]
 [3 4 8]
 [5 6 9]]
