In [9]:
# 1. Numerical Python
import numpy as np
arr_1 = np.array([1,2,3,4,5])
arr_2 =np.array([[1,2,3,4],[5,6,7,8]])
arr_3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [10]:
# 2. Displaying 1D & 2D array & 3D array
print(arr_1,end="\n") 

[1 2 3 4 5]


In [11]:
print(arr_2)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
print(arr_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
