In [6]:
# 1. Finding unique value in array
import numpy as np
arr_1= np.array(['blue','red','orange','red','pink','pink','orange','Red',8])
print(arr_1);print("")
print("UNIQUE_VALUES:" ,np.unique(arr_1))

['blue' 'red' 'orange' 'red' 'pink' 'pink' 'orange' 'Red' '8']

UNIQUE_VALUES: ['8' 'Red' 'blue' 'orange' 'pink' 'red']


In [7]:
# 2. specified size of random values array
arr = np.random.rand(5,5) 
print(arr)

[[0.02970844 0.27475014 0.24892955 0.26312672 0.5194857 ]
 [0.61481195 0.77801964 0.59906958 0.34728584 0.07002241]
 [0.25900636 0.60117468 0.85480226 0.05219027 0.756084  ]
 [0.95384305 0.76809663 0.95850099 0.89001709 0.72940602]
 [0.40570402 0.60178436 0.37304405 0.15807067 0.30889997]]


In [8]:
# 3. specified size of standard normal random variable
rand_1 = np.random.randn() 
print(rand_1);print('')
rand_2= np.random.randn(3,2)
print(rand_2)

-0.36876353147930435

[[ 1.01140875 -0.0822069 ]
 [-0.90863555  0.38496274]
 [-0.52335353 -0.67439442]]


In [12]:
# 4. statistical functions for Standard Deviation & Mean
print(np.std(rand_2)); print("")
arr_1=np.arange(1,11)
print(np.mean(arr_1))

0.6617685205949247

5.5


In [15]:
# 5. Finding min & max
print("Array: ",arr_1)
print(np.min(arr_1),np.max(arr_1),sep="\n")

Array:  [ 1  2  3  4  5  6  7  8  9 10]
1
10


In [21]:
# 6. selecting specific values in array
print(arr[0:2,1:3])

[[0.27475014 0.24892955]
 [0.77801964 0.59906958]]


In [27]:
# 7. update some vaues in array
arr[0:6,3:5] = [1,2]
print(arr)

[[0.02970844 0.27475014 0.24892955 1.         2.        ]
 [0.61481195 0.77801964 0.59906958 1.         2.        ]
 [0.25900636 0.60117468 0.85480226 1.         2.        ]
 [0.95384305 0.76809663 0.95850099 1.         2.        ]
 [0.40570402 0.60178436 0.37304405 1.         2.        ]]


In [28]:
# 8. erasing all values
arr[:]=0
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
# 9. filtering out required
arr=np.arange(-10,20)           # array with negative & positive values
print(arr)
print("")
print(arr[arr>0])                     # array with all positive values

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10  11  12  13  14  15  16  17  18  19]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [36]:
# 10. updating array
arr[arr<0]=0
print(arr)

[ 0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  5  6  7  8  9 10 11 12 13
 14 15 16 17 18 19]
