In [11]:
# 1. Shape of array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]]])
print(arr.shape)

(1, 2, 3)


In [29]:
vec = np.array([[[1, 2, 3,4]],[[2,3,1,10]],[[8,5,7,9]]], ndmin=4)
print(vec)

[[[[ 1  2  3  4]]

  [[ 2  3  1 10]]

  [[ 8  5  7  9]]]]


In [31]:
print('Shape of array :', vec.shape) 

Shape of array : (1, 3, 1, 4)


In [41]:
# 2. Reshaping array
newarr=vec.reshape(1,3,4)
print(newarr)

[[[ 1  2  3  4]
  [ 2  3  1 10]
  [ 8  5  7  9]]]


In [42]:
print('Shape of array :', newarr.shape) 

Shape of array : (1, 3, 4)


In [55]:
# 3. calling view after reshaping
select=vec.view()
print(select.reshape(1,2,6))

[[[ 1  2  3  4  2  3]
  [ 1 10  8  5  7  9]]]


In [57]:
print(select.base)

[[[ 1  2  3  4]]

 [[ 2  3  1 10]]

 [[ 8  5  7  9]]]


In [61]:
# 4. flexible reshaping with unknown axis 
print(newarr.reshape(2,2,-1))

[[[ 1  2  3]
  [ 4  2  3]]

 [[ 1 10  8]
  [ 5  7  9]]]


In [62]:
# 5. Flattening array to 1D
print(vec.reshape(-1))

[ 1  2  3  4  2  3  1 10  8  5  7  9]
