In [1]:
# 1. Search elements of array
import numpy as np
arr=np.array([2,3,4,5,6,7,9,8,11])
key=7
print(np.where(arr == key))

(array([5], dtype=int64),)


In [7]:
# 2. Search range of elements
arr=np.arange(1,21,1.5)
print(arr)

[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13.  14.5 16.  17.5 19.  20.5]


In [8]:
print("Even number indices: ")
print(np.where(arr%2==0))

Even number indices: 
(array([ 2,  6, 10], dtype=int64),)


In [9]:
print("Odd number indices: ")
print(np.where(arr%2 !=0))

Odd number indices: 
(array([ 0,  1,  3,  4,  5,  7,  8,  9, 11, 12, 13], dtype=int64),)


In [12]:
# 3. searchsorted
arr=np.arange(22,45,2)
print(arr)

[22 24 26 28 30 32 34 36 38 40 42 44]


In [13]:
# 4. index values for insertion
new=np.searchsorted(arr,[41,27,35])
print(new)

[10  3  7]


In [20]:
# 5. inserting array elements
a = np.array([[1,2],[3,4],[5,6]]) 
print (np.insert(a,3,[11,12]))

[ 1  2  3 11 12  4  5  6]
