In [1]:
# 1. Crerating arrays with numerical values
import numpy as np
new=np.arange(6)
print(new)

[0 1 2 3 4 5]


In [19]:
new=np.arange(1.1,11,1.52,dtype=float)
print(new)

[ 1.1   2.62  4.14  5.66  7.18  8.7  10.22]


In [16]:
# 2. rearranging array
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [50]:
# 3. splitting arrays
new=np.arange(1,9)
print("Origina Array: ",new)
split=np.array_split(new,4)
print("Splitted Array: ",split)

Origina Array:  [1 2 3 4 5 6 7 8]
Splitted Array:  [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [51]:
own=np.arange(20,43,2).reshape(6,2)
print(own)

[[20 22]
 [24 26]
 [28 30]
 [32 34]
 [36 38]
 [40 42]]


In [57]:
# 4. printing particular index of splitted array
new=np.array_split(own,3)
print(new[1])

[[28 30]
 [32 34]]


In [87]:
# 5. splitting across y-axis
new=np.arange(20).reshape(2,5,2)
print(new)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [88]:
print(np.vsplit(new,2))

[array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]]), array([[[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])]


In [89]:
print(np.vsplit(new,2)[0])

[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
